version: '3.1'

services:

  db:
    container_name: mysql-test
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'recipesapi-test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'


  phpmyadmin:
    container_name: phpmyadmin-test
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1

