# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    exceptions:
        App\Exceptions\ImagesNotFoundException: { code: 404, hidden: false, }
        App\Exceptions\AuthenticationException: { code: 401, hidden: false, }
        App\Exceptions\CuisineNotFoundException: {code: 403, hidden: false,}
        App\Exceptions\ReviewNotFoundException: {code: 405, hidden: false,}
        App\Exceptions\RecipeNotFoundException: { code: 404, hidden: false, }
        App\Exceptions\NewsletterClientExistsException: {code: 405, hidden: false,}
        App\Exceptions\SubmitReviewAccessException: {code: 408, hidden: false,}
        App\Exceptions\ChangeReviewAccessException: {code: 408, hidden: false,}
        App\Exceptions\UserExistsException: { code: 405, hidden: false, }
        App\Exceptions\UserReviewNotExistsException: { code: 405, hidden: false}
        App\Exceptions\RecipeAlreadyPublishException: { code: 405, hidden: false, }
        App\Exceptions\RecipeAlreadyUnPublishException: { code: 405, hidden: false, }
        App\Exceptions\UserNotFoundException: { code: 407, hidden: false, }
        App\Exceptions\LoginException: {code: 404, hidden: false}
        App\Exceptions\NewsSubscribeNotConvertException: {code: 406, hidden: false}
        App\Exceptions\UserDataNotConvertException: { code: 406, hidden: false }
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ExceptionHandler\ExceptionMappingResolver:
        arguments: ['%exceptions%']

#    App\Listener\ApiExceptionListener:
#        tags:
#            - {name: kernel.event_listener, event: kernel.exception, priority: 10}

    App\Listener\ValidationExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 11 }
